openapi: 3.0.1
info:
  contact:
    email: marcus.gallegos@ucdenver.edu
  description: 'This really is a simple demo server meant to display the features
    of apigen. '
  license:
    name: Apache 2.0
  title: Senior Design PetStore
  version: 1.0.5
servers:
- url: https://petstore.swagger.io/v2
tags:
- description: Everything about your Pets
  externalDocs:
    description: Find out more
    url: http://swagger.io
  name: pet
- description: Access to Petstore orders
  name: store
- description: Operations about user
  externalDocs:
    description: Find out more about our store
    url: http://swagger.io
  name: user
paths:
  /pet:
    delete:
      operationId: petDELETE
      responses:
        "400":
          content: {}
          description: Unknown error
        "404":
          content: {}
          description: Pet not found
        "405":
          content: {}
          description: Validation exception
      summary: Deletes a pet
      tags: []
      x-eov-operation-handler: controllers/DefaultController
    get:
      description: Get's documents where name is 'Fido'
      operationId: getPet
      parameters:
      - description: The document ID (name) of pet to get
        in: query
        name: petName
        schema:
          type: string
      responses:
        "400":
          content: {}
          description: Unknown error
        "404":
          content: {}
          description: Pet not found
        "405":
          content: {}
          description: Validation exception
      summary: get fido
      tags:
      - pet
      x-eov-operation-handler: controllers/PetController
    put:
      operationId: petPUTT
      responses:
        "400":
          content: {}
          description: Unknown error
        "404":
          content: {}
          description: Pet not found
        "405":
          content: {}
          description: Validation exception
      summary: Updates a pet
      tags: []
      x-eov-operation-handler: controllers/DefaultController
  /store:
    delete:
      operationId: storeDELETE
      responses:
        "400":
          content: {}
          description: Unknown error
        "404":
          content: {}
          description: Pet not found
        "405":
          content: {}
          description: Validation exception
      summary: this is a delete req for store "update the summary of this endpoint"
      tags: []
      x-eov-operation-handler: controllers/DefaultController
    get:
      operationId: getStore
      responses:
        "400":
          content: {}
          description: Unknown error
        "404":
          content: {}
          description: Pet not found
        "405":
          content: {}
          description: Validation exception
      summary: get request for store
      tags: []
      x-eov-operation-handler: controllers/DefaultController
components:
  schemas:
    ApiResponse:
      properties:
        code:
          format: int32
          type: integer
        type:
          type: string
        message:
          type: string
      type: object
    Category:
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
      type: object
      xml:
        name: Category
    Pet:
      properties:
        id:
          format: int64
          type: integer
        category:
          $ref: '#/components/schemas/Category'
        name:
          example: doggie
          type: string
        photoUrls:
          items:
            type: string
            xml:
              name: photoUrl
          type: array
          xml:
            wrapped: false
        tags:
          items:
            $ref: '#/components/schemas/Tag'
          type: array
          xml:
            wrapped: false
        status:
          description: pet status in the store
          enum:
          - available
          - pending
          - sold
          type: string
      required:
      - name
      - photoUrls
      type: object
      xml:
        name: Pet
    Tag:
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
      type: object
      xml:
        name: Tag
    Order:
      properties:
        id:
          format: int64
          type: integer
        petId:
          format: int64
          type: integer
        quantity:
          format: int32
          type: integer
        shipDate:
          format: date-time
          type: string
        status:
          description: Order Status
          enum:
          - placed
          - approved
          - delivered
          type: string
        complete:
          type: boolean
      type: object
      xml:
        name: Order
    User:
      properties:
        id:
          format: int64
          type: integer
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        phone:
          type: string
        userStatus:
          description: User Status
          format: int32
          type: integer
      type: object
      xml:
        name: User
  securitySchemes:
    api_key:
      in: header
      name: api_key
      type: apiKey
    petstore_auth:
      flows:
        implicit:
          authorizationUrl: https://petstore.swagger.io/oauth/authorize
          scopes:
            read:pets: read your pets
            write:pets: modify pets in your account
      type: oauth2
